version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/qadez11/next-template:main
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    restart: unless-stopped